services:
  - type: web
    name: todo-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start

  - type: static_site
    name: todo-frontend
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: todo-backend
          property: host
